username: timvideos
repo: HDMI2USB-numato-opsis-docs
branch: master
destination: ../opsis.hdmi2usb.tv

# Site title and subtitle. This is used in _includes/header.html
title: 'Numato Opsis'
subtitle: 'Developer Documentation'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: 'numato-opsis'

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-23123757-5'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/timvideos/HDMI2USB-numato-opsis-sample-code'

# Default categories (in order) to appear in the navigation
sections: [
    ['getting-started', 'Getting Started'],
    ['features', 'Features'],
    ['info', 'More Information'],
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

include:
  - getting-started
  - features

# Use the redcarpet Markdown renderer
markdown: redcarpet
kramdown: 
  parse_block_html: true
  input: GFM

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'tables',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'underline',
        'highlight',
        'footnotes',
        'with_toc_data',
    ]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      disqus: 1

gems:
  - jekyll-redirect-from
